language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_API=24
    - ANDROID_BUILD_TOOLS=24.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - openssl aes-256-cbc -K $encrypted_ae8e00e94dc9_key -iv $encrypted_ae8e00e94dc9_iv
     -in ApiSdkDev/mt-data-api-sdk-android/src/test/resources/server.txt.enc -out ApiSdkDev/mt-data-api-sdk-android/src/test/resources/server.txt
     -d
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

script: cd ApiSdkDev && ./gradlew :mt-data-api-sdk-android:testReleaseUnitTest
